apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xprivateendpoints.acme.co
spec:
  compositeTypeRef:
    apiVersion: acme.co/v1alpha1
    kind: XPrivateEndpoint
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-platform-apiprivateendpoints-composer
    step: privateendpoints-composer
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
