apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: platform-api
spec:
  dependsOn:
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.0.0'
  - provider: xpkg.upbound.io/upbound/provider-azure-network
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-web
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azapi
    version: v0.1.0
  - provider: xpkg.upbound.io/upbound/provider-azure-compute
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-keyvault
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-cosmosdb
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-sql
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-servicebus
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-storage
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-cache
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-operationalinsights
    version: v1.8.0
  - provider: xpkg.upbound.io/upbound/provider-azure-insights
    version: v1.8.0
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/acmeco/platform-api
  source: github.com/upbound/project-template
