apiVersion: acme.co/v1alpha1
kind: Firewall
metadata:
  name: example
  namespace: default
spec:
  parameters:
    resourceGroup: 'example-wpzb2-p6mtb'
    location: "eastus"
    vnetName: "example-wpzb2-g8xs4"
    firewallSubnetPrefix: "10.0.200.0/24"
