apiVersion: acme.co/v1alpha1
kind: ASE
metadata:
  name: example
  namespace: default
spec: 
  parameters:
    location: "us-east1"
    vnetName: "my-vnet"
    vnetRouteName: "route"
    aseSubnetAddressPrefix: "prefix"
    dedicatedHostCount: 0
    zoneRedundant: false