apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.acme.co
spec:
  claimNames:
    kind: Network
    plural: networks
  group: acme.co
  names:
    categories:
    - crossplane
    kind: XNetwork
    plural: xnetworks
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Network is the Schema for the Network API.
        properties:
          spec:
            description: NetworkSpec defines the desired state of Network.
            properties:
              parameters:
                properties:
                  existentVnetName:
                    type: string
                  location:
                    type: string
                  resourceGroup:
                    type: string
                  vnetAddressPrefix:
                    type: string
                type: object
            type: object
          status:
            description: NetworkStatus defines the observed state of Network.
            type: object
        required:
        - spec
        type: object
    served: true
status:
  controllers:
    compositeResourceClaimType:
      apiVersion: ""
      kind: ""
    compositeResourceType:
      apiVersion: ""
      kind: ""
