apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xases.acme.co
spec:
  compositeTypeRef:
    apiVersion: acme.co/v1alpha1
    kind: XASE
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-platform-apiase-composer
    step: ase-composer
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
