apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xjumpboxes.acme.co
spec:
  compositeTypeRef:
    apiVersion: acme.co/v1alpha1
    kind: XJumpbox
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-platform-apijumpbox-composer
    step: jumpbox-composer
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
